a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
print(f"addition:{a+b}")
print(f"subraction:{a-b}")
print(f"multiplication:{a*b}")
print(f"division:{a/b}")
print(f"modulas:{a%b}")
